version: "3"
services:
  api:
    build:
      context: ./api
    command: npm run dev
    volumes:
      - ./api:/usr/src/app
    ports:
      - "80:8080"
    depends_on:
      - api_db
    environment:
      PORT: 8080
      HOST: "0.0.0.0"
      MONGO_URL: "mongodb://api_db:27017/api"
      NODE_ENV: "development"
  api_db:
    image: mongo
    volumes:
      - mongodb_api:/data/db
    ports:
      - "27017:27017"
  frontentd:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
volumes:
  mongodb_api:

  # Записуйте інші сервіси, які можуть бути в вашому середовищі розробки
