version: "3"
services:
  api:
    build:
      context: ./api
    ports:
      - "80:8080"
    depends_on:
      - api_db
    environment:
      PORT: 8080
      HOST: "0.0.0.0"
      MONGO_URL: "mongodb://api_db:27017/api"

  api_db:
    image: mongo
    volumes:
      - mongodb_api:/data/db
    ports:
      - "27017:27017"
  frontentd:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    command: serve -s build -l 3000
    ports:
      - "3000:3000"
    depends_on:
      - api
volumes:
  mongodb_api:
