version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - "80:8080"
    depends_on:
      - api_db
    environment:
      PORT: 8080
      HOST: "0.0.0.0"
      MONGO_URL: "mongodb://api_db:27017/api"

  api_db:
    image: mongo
    ports:
      - "27017:27017"

  # Додайте інші сервіси, які можуть бути в вашому проекті

