version: "3"
services:
  api:
    build:
      context: ./api
    command: npm run dev
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - api_db
    environment:
      PORT: 8080
      HOST: "0.0.0.0"
      MONGO_URL: "mongodb://api_db:27017/api"
      NODE_ENV: "development"
  nginx:
    image: nginx:1-alpine
    container_name: websystem-docker-nginx
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api
  api_db:
    image: mongo
    volumes:
      - mongodb_api:/data/db
    ports:
      - "27017:27017"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
volumes:
  mongodb_api: